CREATE DATABASE `grupo3` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
create USER 'grupo3'@'localhost' IDENTIFIED WITH mysql_native_password BY 'grupo3';
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE VIEW, DELETE, DROP, INDEX, INSERT, SELECT, SHOW DATABASES, SHOW VIEW, TRIGGER, UPDATE on *.* TO 'grupo3'@'localhost';